# Generated by Django 4.1.2 on 2022-11-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_value',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='data',
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_unit',
            field=models.CharField(choices=[('C', 'Celsius'), ('F', 'Fahrenheit'), ('m', 'Meters'), ('km', 'Kilometers')], default='C', max_length=5),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='date_registered',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='value',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
    ]
