# Generated by Django 4.1.2 on 2022-11-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_remove_sensor_sensor_value_remove_sensordata_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='upd_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
