# Generated by Django 4.1.3 on 2022-11-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_alter_sensor_pub_date_alter_sensor_upd_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='time_registered',
            field=models.TimeField(auto_now=True),
        ),
    ]
