# Generated by Django 4.1.3 on 2022-11-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_alter_sensordata_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
