# Generated by Django 4.1.2 on 2022-10-30 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=200)),
                ('sensor_value', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal_app.sensor')),
            ],
        ),
        migrations.DeleteModel(
            name='ArduinoSensor',
        ),
    ]
