# Generated by Django 4.1.2 on 2022-10-31 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal_app', '0002_sensor_sensordata_delete_arduinosensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='upd_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
